//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	/// <summary>
	/// Class that represents a given position on the GameBoard.
	/// </summary>
	public class BoardPosition
	{
		/// <summary>
		/// The row in the BoardPlane that this 
		/// BoardPosition is located in.
		/// </summary>
		public int Row;

		/// <summary>
		/// The column in the BoardPlane that this
		/// BoardPosition is located in.
		/// </summary>
		public int Column;

		/// <summary>
		/// The vertical level that this BoardPosition
		/// is located in.
		/// </summary>
		public int Level;

		/// <summary>
		/// Create a new BoardPosition at the provided row, column, and level.
		/// </summary>
		public BoardPosition (int row, int column, int level)
		{
			this.Row    = row;
			this.Column = column;
			this.Level  = level;
		}
	}
}

